vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
vim.keymap.set('n', '<leader>rw', ':s/\\v(.{80})/\\1\\r/g<CR>";', { desc = 'Wrap around 80' })
vim.keymap.set('n', '<leader>sr', ':%s/<C-r><C-w>/<C-r><C-w>/gI<Left><Left><Left>', { desc = 'Find/Replace under cursor' })
vim.keymap.set({ 'n', 'x' }, '<leader>sR', function()
  require('grug-far').open { visualSelectionUsage = 'operate-within-range' }
end, { desc = 'grug-far: Search within range' })
-- use shift to select text
vim.keymap.set('n', '<S-Down>', 'v<Down>')
vim.keymap.set('n', '<S-Up>', 'v<Up>')
vim.keymap.set('n', '<S-Left>', 'v<Left>')
vim.keymap.set('n', '<S-Right>', 'v<Right>')
vim.keymap.set('v', '<S-Down>', '<Down>')
vim.keymap.set('v', '<S-Up>', '<Up>')
vim.keymap.set('v', '<S-Left>', '<Left>')
vim.keymap.set('v', '<S-Right>', '<Right>')
vim.keymap.set('i', '<S-Down>', '<Esc>v<Down>')
vim.keymap.set('i', '<S-Up>', '<Esc>v<Up>')
vim.keymap.set('i', '<S-Left>', '<Esc>v<Left>')
vim.keymap.set('i', '<S-Right>', '<Esc>v<Right>')
vim.keymap.set('n', '<leader>xl', vim.diagnostic.open_float, { desc = 'Show line diagnostics' })
