local options = {
  showmode = false,
  confirm = true,
  autoindent = true,
  breakindent = true,
  cc = '80,120',
  cmdheight = 0,
  completeopt = { 'menu', 'menuone', 'noselect' },
  copyindent = true,
  cursorline = false,
  encoding = 'utf-8',
  equalalways = true,
  expandtab = true,
  smartindent = true,
  fileencoding = 'utf-8',
  fillchars = {
    diff = '╱',
    eob = ' ',
    fold = ' ',
    foldclose = '',
    foldopen = '',
    horiz = '━',
    horizdown = '┳',
    horizup = '┻',
    msgsep = '‾',
    vert = '┃',
    verthoriz = '╋',
    vertleft = '┫',
    vertright = '┣',
  },
  foldcolumn = '1',
  foldenable = true,
  foldexpr = 'v:lua.vim.treesitter.foldexpr()',
  foldlevel = 99,
  foldlevelstart = -1,
  foldmethod = 'expr',
  formatexpr = "v:lua.require'conform'.formatexpr()",
  hidden = true,
  ignorecase = true,
  inccommand = 'split',
  incsearch = true,
  list = true,
  listchars = 'tab:→ ,nbsp:␣,trail:•,extends:⟩,precedes:⟨',
  -- listchars = { tab = '» ', trail = '·', nbsp = '␣' },
  modeline = true,
  modelines = 100,
  mouse = 'a',
  mousemodel = 'extend',
  number = true,
  preserveindent = true,
  pumheight = 10,
  redrawtime = 10000,
  report = 9001,
  scrolloff = 10,
  sessionoptions = 'blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions',
  shiftwidth = 2,
  showbreak = '↪\\',
  signcolumn = 'yes:2',
  smartcase = true,
  spell = true,
  splitbelow = true,
  splitright = true,
  startofline = true,
  swapfile = false,
  synmaxcol = 125,
  tabstop = 2,
  termguicolors = true,
  timeoutlen = 100,
  ttyfast = true,
  undofile = true,
  updatetime = 100,
  wildignorecase = true,
  wrap = false,
}

vim.schedule(function()
  vim.o.clipboard = 'unnamedplus'
end)

for k, v in pairs(options) do
  vim.opt[k] = v
end
