return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    preset = 'modern',
    delay = 0,
    icons = {
      mappings = vim.g.have_nerd_font,
      group = ' ',
      separator = '󰜴 ',
      colors = true,
    },
    win = {
      border = 'rounded',
      padding = { 1, 2 },
      title = true,
      title_pos = 'center',
    },
    layout = {
      width = { min = 24, max = 42 },
      spacing = 2,
    },
    spec = {
      { '<leader>p', group = 'Programming', icon = { icon = '󰘧 ', color = 'orange' } },
      { '<leader>pr', group = 'Run / Rename', icon = { icon = '󰑕 ', color = 'blue' } },
      { '<leader>pv', group = 'Environments / Packages', icon = { icon = '󰏖 ', color = 'green' } },
      { '<leader>c', group = 'C / C++ Reference', icon = { icon = '󰙲 ', color = 'blue' } },
      { '<leader>D', group = 'Debug', icon = { icon = '󰃤 ', color = 'red' } },
      { '<leader>f', group = 'Folds', icon = { icon = '󰘿 ', color = 'yellow' } },
      { '<leader>g', group = 'Git', icon = { icon = '󰊢 ', color = 'orange' } },
      { '<leader>gh', group = 'Git Hunks', icon = { icon = '󰊢 ', color = 'orange' }, mode = { 'n', 'v' } },
      { '<leader>o', group = 'Notes / AI', icon = { icon = '󰚩 ', color = 'purple' }, mode = { 'n', 'v' } },
      { '<leader>a', group = 'Avante', icon = { icon = '󱜸 ', color = 'magenta' }, mode = { 'n', 'v' } },
      { '<leader>r', group = 'Refactor / Format', icon = { icon = '󰙅 ', color = 'cyan' }, mode = { 'n', 'v' } },
      { '<leader>s', group = 'Search', icon = { icon = '󰍉 ', color = 'green' }, mode = { 'n', 'v' } },
      { '<leader>S', group = 'Sessions', icon = { icon = '󰆓 ', color = 'azure' } },
      { '<leader>t', group = 'Tools', icon = { icon = '󰆍 ', color = 'purple' } },
      { '<leader>u', group = 'UI Toggles', icon = { icon = '󰙵 ', color = 'cyan' } },
      { '<leader>x', group = 'Diagnostics / Lists', icon = { icon = '󱖫 ', color = 'green' } },
      { '<leader>.', group = 'Scratch', icon = { icon = '󰏫 ', color = 'yellow' } },
      { '<leader>e', desc = 'File Explorer', icon = { icon = '󰙅 ', color = 'cyan' } },
      { '<leader>-', desc = 'File Explorer (Oil)', icon = { icon = '󰙅 ', color = 'cyan' } },
      { '<leader>b', desc = 'Buffers', icon = { icon = '󰈔 ', color = 'cyan' } },
      { '<leader>q', desc = 'Delete Buffer', icon = { icon = '󰅖 ', color = 'red' } },
      { '<leader>z', desc = 'Toggle Zoom', icon = { icon = '󰁌 ', color = 'blue' } },
      { '<leader>Z', desc = 'Toggle Zen Mode', icon = { icon = '󱅻 ', color = 'cyan' } },
      { '<leader>N', desc = 'Neovim News', icon = { icon = '󰎕 ', color = 'green' } },
      { '<leader>y', desc = 'Registers', icon = { icon = '󱓥 ', color = 'yellow' } },
      { '<leader>/', desc = 'Buffer Lines', icon = { icon = '󰗧 ', color = 'green' } },
      { '<leader>:', desc = 'Command History', icon = { icon = '󰆍 ', color = 'purple' } },
      { '<leader>n', desc = 'Notification History', icon = { icon = '󰵅 ', color = 'blue' } },
      { '<leader><leader>', desc = 'Peep', icon = { icon = '󰈈 ', color = 'yellow' } },

      -- Nvim 0.12 default LSP keymaps (documented here for discoverability)
      { 'grn', desc = 'LSP Rename' },
      { 'gra', desc = 'LSP Code Action', mode = { 'n', 'v' } },
      { 'grr', desc = 'LSP References' },
      { 'gri', desc = 'LSP Implementation' },
      { 'grt', desc = 'LSP Type Definition' },
      { 'grx', desc = 'LSP Run Codelens' },
      { 'gO', desc = 'LSP Document Symbols' },
      { 'gx', desc = 'Open link / LSP documentLink' },
    },
  },
}
