return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    preset = 'modern',
    delay = 0,
    icons = {
      mappings = true,
      group = ' ',
      separator = ' ',
      colors = true,
    },
    spec = {
      { '<leader>p', group = '[P]rogramming', icon = { icon = ' ', color = 'orange' } },
      { '<leader>pr', group = '[R]un / Rename', icon = { icon = ' ', color = 'blue' } },
      { '<leader>pv', group = '[V]env / Packages', icon = { icon = ' ', color = 'green' } },
      { '<leader>c', group = '[C]++ Reference', icon = { icon = '󰙲 ', color = 'blue' } },
      { '<leader>D', group = '[D]ebug', icon = { icon = '󰃤 ', color = 'red' } },
      { '<leader>f', group = '[F]olds', icon = { icon = ' ', color = 'yellow' } },
      { '<leader>g', group = '[G]it', icon = { icon = ' ', color = 'orange' } },
      { '<leader>gh', group = 'Git [H]unks', icon = { icon = '󰊢 ', color = 'orange' } },
      { '<leader>o', group = '[O]penCode', icon = { icon = ' ', color = 'purple' } },
      { '<leader>r', group = '[R]eplace/Refactor', icon = { icon = ' ', color = 'cyan' } },
      { '<leader>s', group = '[S]earch', icon = { icon = ' ', color = 'green' } },
      { '<leader>S', group = '[S]ession', icon = { icon = ' ', color = 'azure' } },
      { '<leader>t', group = '[T]ools', icon = { icon = ' ', color = 'purple' } },
      { '<leader>u', group = '[U]I', icon = { icon = '󰙵 ', color = 'cyan' } },
      { '<leader>x', group = '[X] Diagnostics', icon = { icon = '󱖫 ', color = 'green' } },
      { '<leader>.', group = 'Scratch', icon = { icon = '󰏫 ', color = 'yellow' } },
      { '<leader>e', desc = 'File Explorer', icon = { icon = '󰙅 ', color = 'cyan' } },
      { '<leader>-', desc = 'File Explorer (Oil)', icon = { icon = '󰙅 ', color = 'cyan' } },
      { '<leader>b', desc = 'Buffers', icon = { icon = '󰈔 ', color = 'cyan' } },
      { '<leader>q', desc = 'Delete Buffer', icon = { icon = '󰅖 ', color = 'red' } },
      { '<leader>z', desc = 'Toggle Zoom', icon = { icon = '󰁌 ', color = 'blue' } },
      { '<leader>Z', desc = 'Toggle Zen Mode', icon = { icon = '󱅻 ', color = 'cyan' } },
      { '<leader>N', desc = 'Neovim News', icon = { icon = '󰎕 ', color = 'green' } },
      { '<leader>y', desc = 'Registers', icon = { icon = '󱓥 ', color = 'yellow' } },
      { '<leader>/', desc = 'Buffer Lines', icon = { icon = ' ', color = 'green' } },
      { '<leader>:', desc = 'Command History', icon = { icon = ' ', color = 'purple' } },
      { '<leader>n', desc = 'Notification History', icon = { icon = '󰵅 ', color = 'blue' } },
      { '<leader><leader>', desc = 'Peep', icon = { icon = '󰈈 ', color = 'yellow' } },

      -- Nvim 0.12 default LSP keymaps (documented here for discoverability)
      { 'grn', desc = 'LSP Rename' },
      { 'gra', desc = 'LSP Code Action', mode = { 'n', 'v' } },
      { 'grr', desc = 'LSP References' },
      { 'gri', desc = 'LSP Implementation' },
      { 'grt', desc = 'LSP Type Definition' },
      { 'grx', desc = 'LSP Run Codelens' },
      { 'gO',  desc = 'LSP Document Symbols' },
      { 'gx',  desc = 'Open link / LSP documentLink' },
    },
  },
}
